### ISSUE TITLE
Problemas para devolucion de pagos

### ISSUE THREAD

**Issue by Gdesimone74** [mercadopago/sdk-java#107]
Estoy teniendo problemas para realizar devoluciones de pago con el sdk de java 1.0.33

Cuando voy a realizar una devolución realizo esto:

```
Payment payment = Payment.findById(id);
payment.refund();
```

La respuesta que recibo es otra vez el mismo payment pero el status sigue siendo activo.

En caso de querer realizar la devolución pegándole a la api con un post a esta url: 
https://api.mercadopago.com/v1/payments/xxxxxxxxx/refunds?access_token=

la respuesta que recibo es:

```
{
    "message": "Payment not found",
    "error": "not_found",
    "status": 404,
    "cause": [
        {
            "code": 2000,
            "description": "Payment not found",
            "data": null
        }
    ]
} 
```

Saben que puede llegar a estar pasando?

**Comment by fberasategui** [comment]
Es genial que falle todo a la mierda y no te enteres.

> Nota para los owners del SDK: En los lenguajes serios (no golang) cuando las cosas fallan hay que tirar un `exception`.

**Comment by mdevotoaon** [comment]
Me esta pasando lo mismo, hay algun update del tema?
