### ISSUE TITLE
Getting Card Token

### ISSUE THREAD

**Issue by kuidreS** [mercadopago/sdk-java#147]
**Intro**
I have a server-side Java application and I need to get a Card Token.

**Question**
How to get Card Token using MercadoPago Java SDK?

**Comment by delias-silva** [comment]
Hello @kuidreS!

Today, our backend SDKs don't create card tokens. You must use the [Mercado Pago JS SDK] (https://github.com/mercadopago/sdk-js) to create the card token.
This is done for security reasons.

For more details on this type of integration, you can go to [DevSite](https://www.mercadopago.com/developers/en/guides/online-payments/checkout-api/introduction).
