### ISSUE TITLE
Payment.java getAdditionalInfo()

### ISSUE THREAD

**Issue by nicopes** [mercadopago/sdk-java#149]
La clase Payment.java  en sdk-java/src/main/java/com/mercadopago/resources/Payment.java  no tiene el metodo getAdditionalInfo().

**Comment by gdeandradero** [comment]
Hola, vamos hacer los cambios y crear una nueva versión.
Gracias!

**Comment by gdeandradero** [comment]
@nicopes la versión 1.11.1 ya está disponible con los cambios :)
Gracias!

**Comment by nicopes** [comment]
Gracias a ustedes, saludos!
