### ISSUE TITLE
JAVAEE DeploymentException

### ISSUE THREAD

**Issue by DagonGH** [mercadopago/sdk-java#151]
**CDI deployment failure:Exception List with 2 exceptions**

I was upgrade Mercadopago SDK in my JAVA EE 8 project, EJB pom from

```XML
<groupId>com.mercadopago</groupId>
<artifactId>dx-java</artifactId>
<version>1.8.0</version>
 <exclusion>
    <groupId>org.codehaus.plexus</groupId>
    <artifactId>plexus-java</artifactId>
</exclusion>
<exclusion>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>cobertura-maven-plugin</artifactId>
</exclusion>
<exclusion>
    <groupId>org.sonatype.plugins</groupId>
    <artifactId>nexus-staging-maven-plugin</artifactId>
</exclusion>
<exclusion>
    <groupId>org.sonatype.sisu</groupId>
    <artifactId>sisu-inject-plexus</artifactId>
</exclusion>
```
to

```XML
<groupId>com.mercadopago</groupId>
<artifactId>dx-java</artifactId>
<version>1.11.0</version>
```

For some reason when you deploy in **Payara Server**, you get two different error with with codehaus.plexus dependency and sonatype dependency, i was exclude **plexus-java** and **nexus-staging-maven-plugin**, but the deployment is not success. 

Error Stack trace: 

```JAVA
WELD-001409: Ambiguous dependencies for type BeanLocator with qualifiers @Default at injection point [BackedAnnotatedParameter] Parameter 1 of [BackedAnnotatedConstructor] @Inject public org.sonatype.guice.plexus.locators.DefaultPlexusBeanLocator(BeanLocator) at org.sonatype.guice.plexus.locators.DefaultPlexusBeanLocator

 Possible dependencies: 
  - Managed Bean [class org.sonatype.guice.bean.locators.DefaultBeanLocator] with qualifiers [@Any @Default],
  - Managed Bean [class org.sonatype.guice.bean.locators.DefaultBeanLocator] with qualifiers [@Any @Default]

WELD-001408: Unsatisfied dependencies for type Injector with qualifiers @Default at injection point [BackedAnnotatedParameter] Parameter 1 of [BackedAnnotatedMethod] @Inject org.sonatype.guice.plexus.converters.PlexusXmlBeanConverter.setTypeConverterBindings(Injector)
```

OS: Windows 10
JDK: 1.8
javaee-api: 8.0.1
javax.persistence-api: 2.2
javax.ejb-api: 3.2.2
Payara: 5.2020.7

Some idea or example that how use this SDK version in JAVA EE projects? how and why this SDK cause This dependencies error? If the solution is still to exclude these or another ones libraries because they are provided by the application server, what impact does it have on the operation of the SDK?

**Comment by lucmantovani** [comment]
Hello @DagonGH!

The SDK update shouldn't cause any problems with other dependencies.
It should not be the cause of these problems, nor the solution to them, but we are now using a new `artifactId` for our SDK. So if you would like, you could try using the following:
```xml
<groupId>com.mercadopago</groupId>
<artifactId>sdk-java</artifactId>
<version>1.11.1</version>
```

Unfortunately I will not be able to help you more with this issue 😕

**Comment by DagonGH** [comment]
Thank you @lucmantovani, i was find and solve my problem. it was necessary add **maven-javadoc-plugin** like exclusion,  and this works wonder. I suggested  one best solution in this [fork commit](https://github.com/DagonGH/sdk-java/commit/7d9a11990a6db4eca5bfc7baec2ab0904e9fdd45)

You can also check:

[Maven excludes dependency](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html)
